"use client";

import { useState } from "react";
import {
  AlertTriangle,
  ArrowLeft,
  CheckCircle2,
  Download,
  FileText,
  Loader2,
  ShieldAlert,
  UploadCloud,
} from "lucide-react";

const extractedData = [
  ["Invoice Number", "INV-2048"],
  ["Vendor Name", "Orion Business Supplies"],
  ["Invoice Date", "04 June 2026"],
  ["GSTIN / Tax ID", "Missing"],
  ["Subtotal", "₹52,000"],
  ["Tax Amount", "₹9,360"],
  ["Total Amount", "₹61,360"],
  ["Payment Terms", "Net 15"],
];

const issues = [
  {
    title: "Missing GSTIN / Tax ID",
    severity: "High",
    description:
      "The invoice does not contain a valid GSTIN or tax identification number. This may cause tax filing issues.",
  },
  {
    title: "Possible duplicate invoice",
    severity: "Medium",
    description:
      "The invoice number and vendor amount look similar to a previously uploaded document.",
  },
  {
    title: "Vendor address missing",
    severity: "Low",
    description:
      "The vendor address could not be detected from the document. Ask the vendor to include complete billing details.",
  },
  {
    title: "Tax amount requires review",
    severity: "Medium",
    description:
      "The tax amount appears valid mathematically, but compliance fields are incomplete.",
  },
];

function severityStyle(severity: string) {
  if (severity === "High") return "bg-red-400/10 text-red-300 border-red-400/20";
  if (severity === "Medium")
    return "bg-yellow-400/10 text-yellow-300 border-yellow-400/20";
  return "bg-emerald-400/10 text-emerald-300 border-emerald-400/20";
}

export default function AuditPage() {
  const [fileName, setFileName] = useState("");
  const [loading, setLoading] = useState(false);
  const [audited, setAudited] = useState(false);

  function runAudit() {
    setLoading(true);
    setAudited(false);

    setTimeout(() => {
      setLoading(false);
      setAudited(true);
    }, 1600);
  }

  function downloadReport() {
    const report = `
AuditFlow AI - Invoice Audit Report

File Name: ${fileName || "Sample Invoice"}
Compliance Score: 72%
Risk Level: High Risk

Extracted Invoice Data:
${extractedData.map(([label, value]) => `${label}: ${value}`).join("\n")}

Issues Detected:
${issues
  .map(
    (issue, index) =>
      `${index + 1}. ${issue.title}
Severity: ${issue.severity}
Details: ${issue.description}`
  )
  .join("\n\n")}

Recommended Action:
Ask the vendor to resend the invoice with GSTIN, full vendor address, and confirmation that this invoice has not already been submitted or paid.

Generated by AuditFlow AI
`;

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = "auditflow-ai-report.txt";
    link.click();

    URL.revokeObjectURL(url);
  }

  return (
    <main className="min-h-screen bg-slate-950 px-6 py-6 text-white">
      <div className="absolute inset-0 -z-0 bg-[radial-gradient(circle_at_top_left,_rgba(34,211,238,0.18),_transparent_35%),radial-gradient(circle_at_bottom_right,_rgba(239,68,68,0.15),_transparent_35%)]" />

      <div className="relative z-10 mx-auto max-w-7xl">
        <nav className="flex items-center justify-between rounded-3xl border border-white/10 bg-white/[0.04] px-5 py-4 backdrop-blur-xl">
          <a
            href="/"
            className="flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-sm text-slate-300 hover:bg-white/5 hover:text-white"
          >
            <ArrowLeft size={16} />
            Home
          </a>

          <div className="text-center">
            <p className="text-lg font-black">AuditFlow AI</p>
            <p className="text-xs text-slate-400">AI Invoice Audit Studio</p>
          </div>

          <a
            href="/dashboard"
            className="rounded-full bg-cyan-400 px-5 py-2 text-sm font-bold text-slate-950 hover:bg-cyan-300"
          >
            Dashboard
          </a>
        </nav>

        <section className="grid gap-8 pt-10 lg:grid-cols-[0.9fr_1.1fr]">
          <div className="rounded-[2rem] border border-white/10 bg-white/[0.05] p-6 backdrop-blur-xl">
            <div className="mb-6 inline-flex rounded-full border border-cyan-400/30 bg-cyan-400/10 px-4 py-2 text-sm text-cyan-200">
              Upload document
            </div>

            <h1 className="text-5xl font-black tracking-tight">
              Run a smart invoice audit.
            </h1>

            <p className="mt-5 leading-7 text-slate-400">
              Upload an invoice, receipt, or tax document. This MVP currently
              uses mock AI results, but the interface is ready for OCR and LLM
              integration later.
            </p>

            <label className="mt-8 flex cursor-pointer flex-col items-center justify-center rounded-3xl border border-dashed border-cyan-400/40 bg-cyan-400/5 p-10 text-center transition hover:bg-cyan-400/10">
              <input
                type="file"
                accept=".pdf,.png,.jpg,.jpeg"
                className="hidden"
                onChange={(event) => {
                  const file = event.target.files?.[0];
                  if (file) setFileName(file.name);
                }}
              />

              <UploadCloud size={48} className="text-cyan-300" />

              <p className="mt-5 text-xl font-black">
                {fileName || "Choose invoice file"}
              </p>

              <p className="mt-2 text-sm text-slate-400">
                Supports PDF, PNG, JPG, and JPEG
              </p>
            </label>

            <button
              onClick={runAudit}
              disabled={loading}
              className="mt-6 flex w-full items-center justify-center gap-3 rounded-full bg-cyan-400 px-8 py-4 font-black text-slate-950 transition hover:scale-[1.02] hover:bg-cyan-300 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {loading && <Loader2 className="animate-spin" size={20} />}
              {loading ? "Running AI Audit..." : "Run AI Audit"}
            </button>

            <div className="mt-8 grid gap-4 sm:grid-cols-3">
              <div className="rounded-3xl border border-white/10 bg-slate-900/70 p-5">
                <FileText className="text-cyan-300" />
                <p className="mt-4 text-2xl font-black">8</p>
                <p className="text-sm text-slate-400">Fields extracted</p>
              </div>

              <div className="rounded-3xl border border-white/10 bg-slate-900/70 p-5">
                <AlertTriangle className="text-yellow-300" />
                <p className="mt-4 text-2xl font-black">4</p>
                <p className="text-sm text-slate-400">Issues detected</p>
              </div>

              <div className="rounded-3xl border border-white/10 bg-slate-900/70 p-5">
                <ShieldAlert className="text-red-300" />
                <p className="mt-4 text-2xl font-black">High</p>
                <p className="text-sm text-slate-400">Risk level</p>
              </div>
            </div>
          </div>

          <div className="rounded-[2rem] border border-white/10 bg-white/[0.05] p-6 backdrop-blur-xl">
            {!loading && !audited && (
              <div className="flex min-h-[590px] flex-col items-center justify-center text-center">
                <div className="rounded-full border border-white/10 bg-white/[0.04] p-8">
                  <FileText size={64} className="text-slate-400" />
                </div>
                <h2 className="mt-6 text-3xl font-black">
                  Audit report waiting
                </h2>
                <p className="mt-3 max-w-md text-slate-400">
                  Select a file and click Run AI Audit. Your extracted fields,
                  compliance score, and detected issues will appear here.
                </p>
              </div>
            )}

            {loading && (
              <div className="flex min-h-[590px] flex-col items-center justify-center text-center">
                <Loader2 size={64} className="animate-spin text-cyan-300" />
                <h2 className="mt-6 text-3xl font-black">
                  Auditing document...
                </h2>
                <p className="mt-3 max-w-md text-slate-400">
                  Reading invoice structure, checking tax fields, and searching
                  for duplicate patterns.
                </p>
              </div>
            )}

            {audited && (
              <div>
                <div className="flex flex-col justify-between gap-5 border-b border-white/10 pb-6 md:flex-row md:items-center">
                  <div>
                    <p className="text-sm text-slate-400">Compliance Score</p>
                    <h2 className="text-6xl font-black text-cyan-300">72%</h2>
                  </div>

                  <div className="rounded-3xl border border-red-400/20 bg-red-400/10 px-6 py-4 text-red-300">
                    <p className="text-sm text-red-200">Risk Level</p>
                    <p className="text-2xl font-black">High Risk</p>
                  </div>
                </div>

                <div className="mt-6">
                  <h3 className="text-xl font-black">Extracted Invoice Data</h3>

                  <div className="mt-4 grid gap-3 sm:grid-cols-2">
                    {extractedData.map(([label, value]) => (
                      <div
                        key={label}
                        className="rounded-2xl border border-white/10 bg-slate-900/70 p-4"
                      >
                        <p className="text-xs text-slate-500">{label}</p>
                        <p className="mt-1 font-bold">{value}</p>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="mt-8">
                  <h3 className="text-xl font-black">Issues Detected</h3>

                  <div className="mt-4 space-y-3">
                    {issues.map((issue) => (
                      <div
                        key={issue.title}
                        className="rounded-2xl border border-white/10 bg-slate-900/70 p-4"
                      >
                        <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center">
                          <p className="font-black">{issue.title}</p>
                          <span
                            className={`w-fit rounded-full border px-3 py-1 text-xs font-bold ${severityStyle(
                              issue.severity
                            )}`}
                          >
                            {issue.severity}
                          </span>
                        </div>

                        <p className="mt-2 text-sm leading-6 text-slate-400">
                          {issue.description}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="mt-8 rounded-3xl border border-cyan-400/20 bg-cyan-400/10 p-5">
                  <div className="flex gap-3">
                    <CheckCircle2 className="mt-1 text-cyan-300" size={20} />
                    <div>
                      <h4 className="font-black text-cyan-200">
                        Recommended Action
                      </h4>
                      <p className="mt-2 text-sm leading-6 text-slate-300">
                        Ask the vendor to resend the invoice with GSTIN, full
                        vendor address, and confirmation that this invoice has
                        not already been submitted or paid.
                      </p>
                    </div>
                  </div>
                </div>

                <div className="mt-6 flex flex-col gap-3 sm:flex-row">
                  <button
                    onClick={downloadReport}
                    className="flex flex-1 items-center justify-center gap-3 rounded-full bg-white px-6 py-4 font-black text-slate-950 transition hover:scale-[1.02] hover:bg-cyan-200"
                  >
                    <Download size={20} />
                    Download Report
                  </button>

                  <a
                    href="/dashboard"
                    className="flex flex-1 items-center justify-center rounded-full border border-white/10 bg-white/[0.04] px-6 py-4 font-black text-white transition hover:scale-[1.02] hover:bg-white/10"
                  >
                    View Dashboard
                  </a>
                </div>
              </div>
            )}
          </div>
        </section>
      </div>
    </main>
  );
}