"use client";

import { useState } from "react";
import {
  AlertTriangle,
  ArrowLeft,
  Bell,
  CheckCircle2,
  Clock,
  Download,
  FileText,
  ShieldAlert,
  Trash2,
} from "lucide-react";

type AlertType = "Risk" | "Review" | "Approval" | "Document" | "System";
type AlertStatus = "Unread" | "Read" | "Resolved";
type Filter = "All" | AlertStatus;

type NotificationItem = {
  id: string;
  title: string;
  message: string;
  type: AlertType;
  status: AlertStatus;
  time: string;
  priority: "Low" | "Medium" | "High";
};

const initialNotifications: NotificationItem[] = [
  {
    id: "NOT-001",
    title: "High-risk invoice detected",
    message:
      "Invoice INV-2048 from Orion Business Supplies has missing GSTIN and requires review.",
    type: "Risk",
    status: "Unread",
    time: "04 June 2026, 10:25 AM",
    priority: "High",
  },
  {
    id: "NOT-002",
    title: "Payment approval pending",
    message:
      "Invoice INV-1027 is waiting for approval after audit verification.",
    type: "Approval",
    status: "Unread",
    time: "04 June 2026, 09:40 AM",
    priority: "Medium",
  },
  {
    id: "NOT-003",
    title: "Duplicate invoice warning",
    message:
      "Metro Logistics invoice has a possible duplicate pattern based on vendor, amount, and date.",
    type: "Review",
    status: "Read",
    time: "03 June 2026, 01:12 PM",
    priority: "Medium",
  },
  {
    id: "NOT-004",
    title: "Batch audit completed",
    message:
      "Batch audit processed 4 documents with 1 high-risk invoice and 2 warning items.",
    type: "Document",
    status: "Read",
    time: "03 June 2026, 11:35 AM",
    priority: "Low",
  },
  {
    id: "NOT-005",
    title: "Review threshold updated",
    message:
      "The compliance review threshold was changed to 75% in workspace settings.",
    type: "System",
    status: "Resolved",
    time: "03 June 2026, 05:40 PM",
    priority: "Low",
  },
];

function priorityClass(priority: NotificationItem["priority"]) {
  if (priority === "High") {
    return "border-red-400/20 bg-red-400/10 text-red-300";
  }

  if (priority === "Medium") {
    return "border-yellow-400/20 bg-yellow-400/10 text-yellow-300";
  }

  return "border-emerald-400/20 bg-emerald-400/10 text-emerald-300";
}

function statusClass(status: AlertStatus) {
  if (status === "Unread") {
    return "border-cyan-400/20 bg-cyan-400/10 text-cyan-300";
  }

  if (status === "Read") {
    return "border-yellow-400/20 bg-yellow-400/10 text-yellow-300";
  }

  return "border-emerald-400/20 bg-emerald-400/10 text-emerald-300";
}

function typeIcon(type: AlertType) {
  if (type === "Risk") return ShieldAlert;
  if (type === "Review") return AlertTriangle;
  if (type === "Approval") return CheckCircle2;
  if (type === "Document") return FileText;
  return Bell;
}

export default function NotificationsPage() {
  const [notifications, setNotifications] =
    useState<NotificationItem[]>(initialNotifications);
  const [filter, setFilter] = useState<Filter>("All");

  const filters: Filter[] = ["All", "Unread", "Read", "Resolved"];

  const filteredNotifications = notifications.filter((item) => {
    if (filter === "All") return true;
    return item.status === filter;
  });

  const unreadCount = notifications.filter(
    (item) => item.status === "Unread"
  ).length;

  const highPriorityCount = notifications.filter(
    (item) => item.priority === "High"
  ).length;

  const resolvedCount = notifications.filter(
    (item) => item.status === "Resolved"
  ).length;

  function updateStatus(id: string, status: AlertStatus) {
    setNotifications((currentItems) =>
      currentItems.map((item) =>
        item.id === id ? { ...item, status } : item
      )
    );
  }

  function removeNotification(id: string) {
    setNotifications((currentItems) =>
      currentItems.filter((item) => item.id !== id)
    );
  }

  function downloadNotificationSummary() {
    const content = `
AuditFlow AI - Notification Summary

${notifications
  .map(
    (item) =>
      `${item.id}
Title: ${item.title}
Type: ${item.type}
Priority: ${item.priority}
Status: ${item.status}
Time: ${item.time}
Message: ${item.message}`
  )
  .join("\n\n")}

Generated by AuditFlow AI
`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const link = window.document.createElement("a");
    link.href = url;
    link.download = "auditflow-ai-notifications.txt";
    link.click();

    URL.revokeObjectURL(url);
  }

  return (
    <main className="min-h-screen bg-slate-950 px-6 py-6 text-white">
      <div className="absolute inset-0 -z-0 bg-[radial-gradient(circle_at_top_left,_rgba(34,211,238,0.18),_transparent_35%),radial-gradient(circle_at_bottom_right,_rgba(239,68,68,0.14),_transparent_35%)]" />

      <div className="relative z-10 mx-auto max-w-7xl">
        <nav className="flex items-center justify-between rounded-3xl border border-white/10 bg-white/[0.04] px-5 py-4 backdrop-blur-xl">
          <a
            href="/dashboard"
            className="flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-sm text-slate-300 hover:bg-white/5 hover:text-white"
          >
            <ArrowLeft size={16} />
            Dashboard
          </a>

          <div className="text-center">
            <p className="text-lg font-black">AuditFlow AI</p>
            <p className="text-xs text-slate-400">Notifications</p>
          </div>

          <button
            onClick={downloadNotificationSummary}
            className="flex items-center gap-2 rounded-full bg-cyan-400 px-5 py-2 text-sm font-bold text-slate-950 hover:bg-cyan-300"
          >
            <Download size={17} />
            Export
          </button>
        </nav>

        <section className="pt-10">
          <div className="grid gap-6 lg:grid-cols-[1fr_0.55fr]">
            <div>
              <div className="mb-6 inline-flex rounded-full border border-cyan-400/30 bg-cyan-400/10 px-4 py-2 text-sm text-cyan-200">
                Alert monitoring center
              </div>

              <h1 className="max-w-4xl text-5xl font-black tracking-tight md:text-6xl">
                Track urgent invoice and compliance alerts.
              </h1>

              <p className="mt-5 max-w-2xl leading-7 text-slate-400">
                Monitor high-risk invoices, pending approvals, duplicate
                warnings, batch audit results, and system updates from one
                notification center.
              </p>
            </div>

            <div className="grid gap-4 sm:grid-cols-3 lg:grid-cols-1">
              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <Bell className="text-cyan-300" />
                <p className="mt-4 text-3xl font-black">{unreadCount}</p>
                <p className="text-sm text-slate-400">Unread alerts</p>
              </div>

              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <ShieldAlert className="text-red-300" />
                <p className="mt-4 text-3xl font-black">{highPriorityCount}</p>
                <p className="text-sm text-slate-400">High-priority alerts</p>
              </div>

              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <CheckCircle2 className="text-emerald-300" />
                <p className="mt-4 text-3xl font-black">{resolvedCount}</p>
                <p className="text-sm text-slate-400">Resolved alerts</p>
              </div>
            </div>
          </div>

          <div className="mt-8 rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
            <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center">
              <div>
                <h2 className="text-2xl font-black">Notification Feed</h2>
                <p className="mt-1 text-sm text-slate-400">
                  Review and resolve business alerts.
                </p>
              </div>

              <div className="flex flex-wrap gap-2">
                {filters.map((item) => (
                  <button
                    key={item}
                    onClick={() => setFilter(item)}
                    className={`rounded-full px-4 py-2 text-sm font-bold transition ${
                      filter === item
                        ? "bg-cyan-400 text-slate-950"
                        : "border border-white/10 bg-white/[0.04] text-slate-400 hover:bg-white/10 hover:text-white"
                    }`}
                  >
                    {item}
                  </button>
                ))}
              </div>
            </div>

            <div className="mt-6 grid gap-4">
              {filteredNotifications.map((item) => {
                const Icon = typeIcon(item.type);

                return (
                  <div
                    key={item.id}
                    className="rounded-3xl border border-white/10 bg-slate-900/70 p-5"
                  >
                    <div className="grid gap-5 xl:grid-cols-[1fr_auto] xl:items-center">
                      <div className="flex gap-4">
                        <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-cyan-400/10 text-cyan-300">
                          <Icon size={26} />
                        </div>

                        <div>
                          <div className="flex flex-wrap items-center gap-3">
                            <h3 className="text-xl font-black">{item.title}</h3>

                            <span
                              className={`rounded-full border px-3 py-1 text-xs font-bold ${priorityClass(
                                item.priority
                              )}`}
                            >
                              {item.priority} Priority
                            </span>

                            <span
                              className={`rounded-full border px-3 py-1 text-xs font-bold ${statusClass(
                                item.status
                              )}`}
                            >
                              {item.status}
                            </span>
                          </div>

                          <p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">
                            {item.message}
                          </p>

                          <div className="mt-4 flex items-center gap-2 text-sm text-slate-500">
                            <Clock size={16} />
                            {item.id} · {item.type} · {item.time}
                          </div>
                        </div>
                      </div>

                      <div className="grid gap-3 sm:grid-cols-3 xl:grid-cols-1">
                        <button
                          onClick={() => updateStatus(item.id, "Read")}
                          className="rounded-full border border-white/10 bg-white/[0.04] px-5 py-3 text-sm font-bold text-white hover:bg-white/10"
                        >
                          Mark Read
                        </button>

                        <button
                          onClick={() => updateStatus(item.id, "Resolved")}
                          className="rounded-full bg-emerald-400 px-5 py-3 text-sm font-bold text-slate-950 hover:bg-emerald-300"
                        >
                          Resolve
                        </button>

                        <button
                          onClick={() => removeNotification(item.id)}
                          className="flex items-center justify-center gap-2 rounded-full border border-red-400/20 bg-red-400/10 px-5 py-3 text-sm font-bold text-red-300 hover:bg-red-400/20"
                        >
                          <Trash2 size={17} />
                          Delete
                        </button>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>

            {filteredNotifications.length === 0 && (
              <div className="mt-6 rounded-3xl border border-white/10 bg-slate-900/70 p-10 text-center">
                <Bell className="mx-auto text-cyan-300" size={48} />
                <h3 className="mt-4 text-2xl font-black">
                  No notifications found
                </h3>
                <p className="mt-2 text-sm text-slate-400">
                  There are no alerts matching this filter.
                </p>
              </div>
            )}
          </div>
        </section>
      </div>
    </main>
  );
}