"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import {
  AlertTriangle,
  ArrowLeft,
  CheckCircle2,
  Download,
  FileText,
  ReceiptText,
  ShieldAlert,
  ShieldCheck,
} from "lucide-react";

type ReportItem = {
  id: string;
  invoice: string;
  vendor: string;
  amount: string;
  date: string;
  score: number;
  status: "Clean" | "Warning" | "High Risk";
  issues: string[];
  recommendation: string;
};

const reports: ReportItem[] = [
  {
    id: "RPT-9001",
    invoice: "INV-2048",
    vendor: "Orion Business Supplies",
    amount: "INR 61,360",
    date: "04 June 2026",
    score: 72,
    status: "High Risk",
    issues: [
      "GSTIN / Tax ID is missing from the invoice.",
      "Vendor address could not be verified.",
      "Invoice requires manual review before payment approval.",
    ],
    recommendation:
      "Request a corrected invoice from the vendor before processing payment.",
  },
  {
    id: "RPT-9002",
    invoice: "INV-1025",
    vendor: "Metro Logistics",
    amount: "INR 22,900",
    date: "03 June 2026",
    score: 84,
    status: "Warning",
    issues: [
      "Possible duplicate pattern detected.",
      "Invoice amount matches an earlier document from the same vendor.",
    ],
    recommendation:
      "Verify duplicate status before approval. If valid, mark as reviewed.",
  },
  {
    id: "RPT-9003",
    invoice: "INV-1024",
    vendor: "BrightEdge Supplies",
    amount: "INR 48,500",
    date: "02 June 2026",
    score: 98,
    status: "Clean",
    issues: ["No major compliance issues detected."],
    recommendation:
      "Invoice is eligible for payment approval based on current audit rules.",
  },
];

function statusClass(status: ReportItem["status"]) {
  if (status === "Clean") {
    return "border-emerald-400/20 bg-emerald-400/10 text-emerald-300";
  }

  if (status === "Warning") {
    return "border-yellow-400/20 bg-yellow-400/10 text-yellow-300";
  }

  return "border-red-400/20 bg-red-400/10 text-red-300";
}

function scoreColor(score: number) {
  if (score < 80) return "text-red-300";
  if (score < 90) return "text-yellow-300";
  return "text-emerald-300";
}

export default function PDFReportsPage() {
  const [selectedReport, setSelectedReport] = useState<ReportItem>(reports[0]);

  function generatePDF(report: ReportItem) {
    const pdf = new jsPDF();

    pdf.setFillColor(15, 23, 42);
    pdf.rect(0, 0, 210, 297, "F");

    pdf.setTextColor(34, 211, 238);
    pdf.setFontSize(22);
    pdf.text("AuditFlow AI", 20, 24);

    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(16);
    pdf.text("Invoice Audit Report", 20, 36);

    pdf.setTextColor(148, 163, 184);
    pdf.setFontSize(10);
    pdf.text(`Generated Report ID: ${report.id}`, 20, 45);
    pdf.text("This report summarizes invoice audit findings and risk status.", 20, 52);

    pdf.setDrawColor(34, 211, 238);
    pdf.line(20, 60, 190, 60);

    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(14);
    pdf.text("Invoice Details", 20, 75);

    pdf.setTextColor(226, 232, 240);
    pdf.setFontSize(11);
    pdf.text(`Invoice Number: ${report.invoice}`, 20, 88);
    pdf.text(`Vendor: ${report.vendor}`, 20, 98);
    pdf.text(`Amount: ${report.amount}`, 20, 108);
    pdf.text(`Date: ${report.date}`, 20, 118);

    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(14);
    pdf.text("Compliance Result", 20, 138);

    pdf.setTextColor(226, 232, 240);
    pdf.setFontSize(11);
    pdf.text(`Compliance Score: ${report.score}%`, 20, 151);
    pdf.text(`Risk Status: ${report.status}`, 20, 161);

    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(14);
    pdf.text("Detected Issues", 20, 181);

    pdf.setTextColor(226, 232, 240);
    pdf.setFontSize(10);

    let yPosition = 194;

    report.issues.forEach((issue, index) => {
      const wrappedText = pdf.splitTextToSize(`${index + 1}. ${issue}`, 160);
      pdf.text(wrappedText, 20, yPosition);
      yPosition += wrappedText.length * 7;
    });

    yPosition += 8;

    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(14);
    pdf.text("Recommendation", 20, yPosition);

    yPosition += 12;

    pdf.setTextColor(226, 232, 240);
    pdf.setFontSize(10);
    const recommendationText = pdf.splitTextToSize(report.recommendation, 160);
    pdf.text(recommendationText, 20, yPosition);

    pdf.setTextColor(148, 163, 184);
    pdf.setFontSize(9);
    pdf.text("Generated by AuditFlow AI frontend MVP.", 20, 280);
    pdf.text("Final business use requires backend OCR and AI validation.", 20, 287);

    pdf.save(`${report.id}-${report.invoice}-audit-report.pdf`);
  }

  function generateAllReportsPDF() {
    const pdf = new jsPDF();

    reports.forEach((report, index) => {
      if (index > 0) {
        pdf.addPage();
      }

      pdf.setFillColor(15, 23, 42);
      pdf.rect(0, 0, 210, 297, "F");

      pdf.setTextColor(34, 211, 238);
      pdf.setFontSize(22);
      pdf.text("AuditFlow AI", 20, 24);

      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(16);
      pdf.text("Invoice Audit Report", 20, 36);

      pdf.setTextColor(148, 163, 184);
      pdf.setFontSize(10);
      pdf.text(`Generated Report ID: ${report.id}`, 20, 45);

      pdf.setDrawColor(34, 211, 238);
      pdf.line(20, 58, 190, 58);

      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(14);
      pdf.text("Invoice Details", 20, 75);

      pdf.setTextColor(226, 232, 240);
      pdf.setFontSize(11);
      pdf.text(`Invoice Number: ${report.invoice}`, 20, 88);
      pdf.text(`Vendor: ${report.vendor}`, 20, 98);
      pdf.text(`Amount: ${report.amount}`, 20, 108);
      pdf.text(`Date: ${report.date}`, 20, 118);
      pdf.text(`Compliance Score: ${report.score}%`, 20, 134);
      pdf.text(`Risk Status: ${report.status}`, 20, 144);

      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(14);
      pdf.text("Detected Issues", 20, 164);

      pdf.setTextColor(226, 232, 240);
      pdf.setFontSize(10);

      let yPosition = 177;

      report.issues.forEach((issue, issueIndex) => {
        const wrappedText = pdf.splitTextToSize(`${issueIndex + 1}. ${issue}`, 160);
        pdf.text(wrappedText, 20, yPosition);
        yPosition += wrappedText.length * 7;
      });

      yPosition += 8;

      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(14);
      pdf.text("Recommendation", 20, yPosition);

      yPosition += 12;

      pdf.setTextColor(226, 232, 240);
      pdf.setFontSize(10);
      const recommendationText = pdf.splitTextToSize(report.recommendation, 160);
      pdf.text(recommendationText, 20, yPosition);
    });

    pdf.save("auditflow-ai-all-audit-reports.pdf");
  }

  return (
    <main className="min-h-screen bg-slate-950 px-6 py-6 text-white">
      <div className="absolute inset-0 -z-0 bg-[radial-gradient(circle_at_top_left,_rgba(34,211,238,0.18),_transparent_35%),radial-gradient(circle_at_bottom_right,_rgba(168,85,247,0.15),_transparent_35%)]" />

      <div className="relative z-10 mx-auto max-w-7xl">
        <nav className="flex items-center justify-between rounded-3xl border border-white/10 bg-white/[0.04] px-5 py-4 backdrop-blur-xl">
          <a
            href="/dashboard"
            className="flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-sm text-slate-300 hover:bg-white/5 hover:text-white"
          >
            <ArrowLeft size={16} />
            Dashboard
          </a>

          <div className="text-center">
            <p className="text-lg font-black">AuditFlow AI</p>
            <p className="text-xs text-slate-400">PDF Reports</p>
          </div>

          <button
            onClick={generateAllReportsPDF}
            className="flex items-center gap-2 rounded-full bg-cyan-400 px-5 py-2 text-sm font-bold text-slate-950 hover:bg-cyan-300"
          >
            <Download size={17} />
            Export All
          </button>
        </nav>

        <section className="pt-10">
          <div className="grid gap-6 lg:grid-cols-[1fr_0.55fr]">
            <div>
              <div className="mb-6 inline-flex rounded-full border border-cyan-400/30 bg-cyan-400/10 px-4 py-2 text-sm text-cyan-200">
                Professional report generation
              </div>

              <h1 className="max-w-4xl text-5xl font-black tracking-tight md:text-6xl">
                Generate clean PDF audit reports.
              </h1>

              <p className="mt-5 max-w-2xl leading-7 text-slate-400">
                Export invoice audit findings, risk status, detected issues, and
                recommendations into PDF documents for finance records.
              </p>
            </div>

            <div className="grid gap-4 sm:grid-cols-3 lg:grid-cols-1">
              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <FileText className="text-cyan-300" />
                <p className="mt-4 text-3xl font-black">{reports.length}</p>
                <p className="text-sm text-slate-400">Available reports</p>
              </div>

              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <ShieldAlert className="text-red-300" />
                <p className="mt-4 text-3xl font-black">
                  {reports.filter((item) => item.status === "High Risk").length}
                </p>
                <p className="text-sm text-slate-400">High-risk reports</p>
              </div>

              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <CheckCircle2 className="text-emerald-300" />
                <p className="mt-4 text-3xl font-black">
                  {reports.filter((item) => item.status === "Clean").length}
                </p>
                <p className="text-sm text-slate-400">Clean reports</p>
              </div>
            </div>
          </div>

          <div className="mt-8 grid gap-6 xl:grid-cols-[1fr_1fr]">
            <div className="rounded-[2rem] border border-white/10 bg-white/[0.05] p-6 backdrop-blur-xl">
              <div className="flex items-center gap-3">
                <ReceiptText className="text-cyan-300" size={30} />
                <div>
                  <h2 className="text-2xl font-black">Select Report</h2>
                  <p className="text-sm text-slate-400">
                    Choose an audit report to preview and export.
                  </p>
                </div>
              </div>

              <div className="mt-8 grid gap-4">
                {reports.map((report) => (
                  <button
                    key={report.id}
                    onClick={() => setSelectedReport(report)}
                    className={`rounded-3xl border p-5 text-left transition ${
                      selectedReport.id === report.id
                        ? "border-cyan-400/40 bg-cyan-400/10"
                        : "border-white/10 bg-slate-900/70 hover:bg-white/[0.06]"
                    }`}
                  >
                    <div className="flex flex-wrap items-center gap-3">
                      <h3 className="text-xl font-black">{report.invoice}</h3>

                      <span
                        className={`rounded-full border px-3 py-1 text-xs font-bold ${statusClass(
                          report.status
                        )}`}
                      >
                        {report.status}
                      </span>
                    </div>

                    <p className="mt-2 text-sm text-slate-400">
                      {report.id} · {report.vendor} · {report.amount}
                    </p>

                    <p className={`mt-4 text-3xl font-black ${scoreColor(report.score)}`}>
                      {report.score}%
                    </p>
                  </button>
                ))}
              </div>
            </div>

            <div className="rounded-[2rem] border border-white/10 bg-white/[0.05] p-6 backdrop-blur-xl">
              <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center">
                <div>
                  <h2 className="text-2xl font-black">PDF Preview</h2>
                  <p className="mt-1 text-sm text-slate-400">
                    Report content before export.
                  </p>
                </div>

                <button
                  onClick={() => generatePDF(selectedReport)}
                  className="flex items-center justify-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-slate-950 hover:bg-cyan-200"
                >
                  <Download size={17} />
                  Download PDF
                </button>
              </div>

              <div className="mt-8 rounded-[1.5rem] border border-white/10 bg-slate-900/80 p-6">
                <div className="flex items-start justify-between gap-4">
                  <div>
                    <p className="text-sm font-bold text-cyan-300">AuditFlow AI</p>
                    <h3 className="mt-2 text-3xl font-black">
                      Invoice Audit Report
                    </h3>
                    <p className="mt-2 text-sm text-slate-500">
                      {selectedReport.id}
                    </p>
                  </div>

                  <span
                    className={`rounded-full border px-3 py-1 text-xs font-bold ${statusClass(
                      selectedReport.status
                    )}`}
                  >
                    {selectedReport.status}
                  </span>
                </div>

                <div className="mt-8 grid gap-4 sm:grid-cols-2">
                  <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-4">
                    <p className="text-xs text-slate-500">Invoice</p>
                    <p className="mt-1 font-black">{selectedReport.invoice}</p>
                  </div>

                  <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-4">
                    <p className="text-xs text-slate-500">Vendor</p>
                    <p className="mt-1 font-black">{selectedReport.vendor}</p>
                  </div>

                  <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-4">
                    <p className="text-xs text-slate-500">Amount</p>
                    <p className="mt-1 font-black">{selectedReport.amount}</p>
                  </div>

                  <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-4">
                    <p className="text-xs text-slate-500">Audit Score</p>
                    <p className={`mt-1 text-2xl font-black ${scoreColor(selectedReport.score)}`}>
                      {selectedReport.score}%
                    </p>
                  </div>
                </div>

                <div className="mt-8">
                  <h4 className="font-black">Detected Issues</h4>

                  <div className="mt-4 grid gap-3">
                    {selectedReport.issues.map((issue) => (
                      <div
                        key={issue}
                        className="flex gap-3 rounded-2xl border border-white/10 bg-white/[0.04] p-4"
                      >
                        <AlertTriangle
                          className="mt-0.5 shrink-0 text-yellow-300"
                          size={18}
                        />
                        <p className="text-sm leading-6 text-slate-300">
                          {issue}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="mt-8 rounded-2xl border border-cyan-400/20 bg-cyan-400/10 p-5">
                  <div className="flex gap-3">
                    <ShieldCheck className="mt-1 shrink-0 text-cyan-300" />
                    <div>
                      <h4 className="font-black text-cyan-200">
                        Recommendation
                      </h4>
                      <p className="mt-2 text-sm leading-6 text-slate-300">
                        {selectedReport.recommendation}
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              <p className="mt-5 text-sm text-slate-500">
                PDF exports are generated in the browser for the current
                frontend MVP.
              </p>
            </div>
          </div>
        </section>
      </div>
    </main>
  );
}