"use client";

import { useState } from "react";
import {
  ArrowLeft,
  CheckCircle2,
  Cloud,
  Database,
  Download,
  FileText,
  Landmark,
  Link2,
  Mail,
  PlugZap,
  RefreshCw,
  ShieldCheck,
  XCircle,
} from "lucide-react";

type IntegrationStatus = "Connected" | "Not Connected" | "Needs Attention";

type IntegrationItem = {
  id: string;
  name: string;
  category: string;
  description: string;
  status: IntegrationStatus;
  lastSync: string;
};

const initialIntegrations: IntegrationItem[] = [
  {
    id: "INT-001",
    name: "Gmail Invoice Import",
    category: "Email",
    description:
      "Import invoice attachments from selected finance mailbox labels.",
    status: "Connected",
    lastSync: "04 June 2026, 10:10 AM",
  },
  {
    id: "INT-002",
    name: "Google Drive",
    category: "Cloud Storage",
    description:
      "Sync invoices and receipts from shared company folders.",
    status: "Connected",
    lastSync: "04 June 2026, 09:45 AM",
  },
  {
    id: "INT-003",
    name: "Tally Export",
    category: "Accounting",
    description:
      "Prepare approved invoice records for accounting system entry.",
    status: "Not Connected",
    lastSync: "Not synced",
  },
  {
    id: "INT-004",
    name: "Zoho Books",
    category: "Accounting",
    description:
      "Send approved invoices and audit summaries to finance records.",
    status: "Needs Attention",
    lastSync: "03 June 2026, 04:25 PM",
  },
  {
    id: "INT-005",
    name: "Bank Statement Upload",
    category: "Payments",
    description:
      "Compare invoice approvals with payment records and bank references.",
    status: "Not Connected",
    lastSync: "Not synced",
  },
];

function statusClass(status: IntegrationStatus) {
  if (status === "Connected") {
    return "border-emerald-400/20 bg-emerald-400/10 text-emerald-300";
  }

  if (status === "Needs Attention") {
    return "border-yellow-400/20 bg-yellow-400/10 text-yellow-300";
  }

  return "border-slate-400/20 bg-slate-400/10 text-slate-300";
}

function categoryIcon(category: string) {
  if (category === "Email") return Mail;
  if (category === "Cloud Storage") return Cloud;
  if (category === "Accounting") return Database;
  if (category === "Payments") return Landmark;
  return PlugZap;
}

export default function IntegrationsPage() {
  const [integrations, setIntegrations] =
    useState<IntegrationItem[]>(initialIntegrations);

  const connectedCount = integrations.filter(
    (item) => item.status === "Connected"
  ).length;

  const notConnectedCount = integrations.filter(
    (item) => item.status === "Not Connected"
  ).length;

  const attentionCount = integrations.filter(
    (item) => item.status === "Needs Attention"
  ).length;

  function connectIntegration(id: string) {
    setIntegrations((currentItems) =>
      currentItems.map((item) =>
        item.id === id
          ? {
              ...item,
              status: "Connected",
              lastSync: "Just now",
            }
          : item
      )
    );
  }

  function disconnectIntegration(id: string) {
    setIntegrations((currentItems) =>
      currentItems.map((item) =>
        item.id === id
          ? {
              ...item,
              status: "Not Connected",
              lastSync: "Not synced",
            }
          : item
      )
    );
  }

  function markNeedsAttention(id: string) {
    setIntegrations((currentItems) =>
      currentItems.map((item) =>
        item.id === id
          ? {
              ...item,
              status: "Needs Attention",
              lastSync: "Sync requires review",
            }
          : item
      )
    );
  }

  function downloadIntegrationSummary() {
    const content = `
AuditFlow AI - Integration Summary

${integrations
  .map(
    (item) =>
      `${item.id}
Name: ${item.name}
Category: ${item.category}
Status: ${item.status}
Last Sync: ${item.lastSync}
Description: ${item.description}`
  )
  .join("\n\n")}

Generated by AuditFlow AI
`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const link = window.document.createElement("a");
    link.href = url;
    link.download = "auditflow-ai-integrations.txt";
    link.click();

    URL.revokeObjectURL(url);
  }

  return (
    <main className="min-h-screen bg-slate-950 px-6 py-6 text-white">
      <div className="absolute inset-0 -z-0 bg-[radial-gradient(circle_at_top_left,_rgba(34,211,238,0.18),_transparent_35%),radial-gradient(circle_at_bottom_right,_rgba(168,85,247,0.15),_transparent_35%)]" />

      <div className="relative z-10 mx-auto max-w-7xl">
        <nav className="flex items-center justify-between rounded-3xl border border-white/10 bg-white/[0.04] px-5 py-4 backdrop-blur-xl">
          <a
            href="/dashboard"
            className="flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-sm text-slate-300 hover:bg-white/5 hover:text-white"
          >
            <ArrowLeft size={16} />
            Dashboard
          </a>

          <div className="text-center">
            <p className="text-lg font-black">AuditFlow AI</p>
            <p className="text-xs text-slate-400">Integrations</p>
          </div>

          <button
            onClick={downloadIntegrationSummary}
            className="flex items-center gap-2 rounded-full bg-cyan-400 px-5 py-2 text-sm font-bold text-slate-950 hover:bg-cyan-300"
          >
            <Download size={17} />
            Export
          </button>
        </nav>

        <section className="pt-10">
          <div className="grid gap-6 lg:grid-cols-[1fr_0.55fr]">
            <div>
              <div className="mb-6 inline-flex rounded-full border border-cyan-400/30 bg-cyan-400/10 px-4 py-2 text-sm text-cyan-200">
                Connected business systems
              </div>

              <h1 className="max-w-4xl text-5xl font-black tracking-tight md:text-6xl">
                Connect invoice audits to finance workflows.
              </h1>

              <p className="mt-5 max-w-2xl leading-7 text-slate-400">
                Manage email imports, cloud storage, accounting exports, and
                payment reconciliation connections from one workspace.
              </p>
            </div>

            <div className="grid gap-4 sm:grid-cols-3 lg:grid-cols-1">
              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <CheckCircle2 className="text-emerald-300" />
                <p className="mt-4 text-3xl font-black">{connectedCount}</p>
                <p className="text-sm text-slate-400">Connected systems</p>
              </div>

              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <XCircle className="text-slate-300" />
                <p className="mt-4 text-3xl font-black">{notConnectedCount}</p>
                <p className="text-sm text-slate-400">Not connected</p>
              </div>

              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <RefreshCw className="text-yellow-300" />
                <p className="mt-4 text-3xl font-black">{attentionCount}</p>
                <p className="text-sm text-slate-400">Needs attention</p>
              </div>
            </div>
          </div>

          <div className="mt-8 grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
            <div className="rounded-[2rem] border border-white/10 bg-white/[0.05] p-6 backdrop-blur-xl">
              <div className="flex items-center gap-3">
                <div className="rounded-2xl bg-cyan-400/10 p-3 text-cyan-300">
                  <PlugZap size={30} />
                </div>

                <div>
                  <h2 className="text-2xl font-black">Available Integrations</h2>
                  <p className="text-sm text-slate-400">
                    Connect, disconnect, and monitor business system links.
                  </p>
                </div>
              </div>

              <div className="mt-8 grid gap-4">
                {integrations.map((item) => {
                  const Icon = categoryIcon(item.category);

                  return (
                    <div
                      key={item.id}
                      className="rounded-3xl border border-white/10 bg-slate-900/70 p-5"
                    >
                      <div className="grid gap-5 xl:grid-cols-[1fr_auto] xl:items-center">
                        <div className="flex gap-4">
                          <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-cyan-400/10 text-cyan-300">
                            <Icon size={26} />
                          </div>

                          <div>
                            <div className="flex flex-wrap items-center gap-3">
                              <h3 className="text-xl font-black">{item.name}</h3>

                              <span
                                className={`rounded-full border px-3 py-1 text-xs font-bold ${statusClass(
                                  item.status
                                )}`}
                              >
                                {item.status}
                              </span>

                              <span className="rounded-full border border-white/10 bg-white/[0.04] px-3 py-1 text-xs font-bold text-slate-300">
                                {item.category}
                              </span>
                            </div>

                            <p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">
                              {item.description}
                            </p>

                            <p className="mt-3 text-sm text-slate-500">
                              {item.id} · Last sync: {item.lastSync}
                            </p>
                          </div>
                        </div>

                        <div className="grid gap-3 sm:grid-cols-3 xl:grid-cols-1">
                          <button
                            onClick={() => connectIntegration(item.id)}
                            className="flex items-center justify-center gap-2 rounded-full bg-emerald-400 px-5 py-3 text-sm font-bold text-slate-950 hover:bg-emerald-300"
                          >
                            <Link2 size={17} />
                            Connect
                          </button>

                          <button
                            onClick={() => markNeedsAttention(item.id)}
                            className="flex items-center justify-center gap-2 rounded-full border border-yellow-400/20 bg-yellow-400/10 px-5 py-3 text-sm font-bold text-yellow-300 hover:bg-yellow-400/20"
                          >
                            <RefreshCw size={17} />
                            Review
                          </button>

                          <button
                            onClick={() => disconnectIntegration(item.id)}
                            className="flex items-center justify-center gap-2 rounded-full border border-red-400/20 bg-red-400/10 px-5 py-3 text-sm font-bold text-red-300 hover:bg-red-400/20"
                          >
                            <XCircle size={17} />
                            Disconnect
                          </button>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

            <div className="grid gap-6">
              <div className="rounded-[2rem] border border-white/10 bg-white/[0.05] p-6 backdrop-blur-xl">
                <div className="flex items-center gap-3">
                  <ShieldCheck className="text-cyan-300" size={28} />
                  <h2 className="text-2xl font-black">Sync Rules</h2>
                </div>

                <div className="mt-6 grid gap-4">
                  <div className="rounded-3xl border border-white/10 bg-slate-900/70 p-5">
                    <h3 className="font-black">Import rules</h3>
                    <p className="mt-2 text-sm leading-6 text-slate-400">
                      Invoice attachments can be imported from approved sources
                      such as finance mailbox labels and shared cloud folders.
                    </p>
                  </div>

                  <div className="rounded-3xl border border-white/10 bg-slate-900/70 p-5">
                    <h3 className="font-black">Approval rules</h3>
                    <p className="mt-2 text-sm leading-6 text-slate-400">
                      Only approved invoices should be exported into accounting
                      and payment workflows.
                    </p>
                  </div>

                  <div className="rounded-3xl border border-white/10 bg-slate-900/70 p-5">
                    <h3 className="font-black">Audit protection</h3>
                    <p className="mt-2 text-sm leading-6 text-slate-400">
                      High-risk invoices should remain blocked from export until
                      reviewed or corrected.
                    </p>
                  </div>
                </div>
              </div>

              <div className="rounded-[2rem] border border-cyan-400/20 bg-cyan-400/10 p-6">
                <div className="flex gap-3">
                  <FileText className="mt-1 shrink-0 text-cyan-300" size={24} />
                  <div>
                    <h3 className="text-xl font-black text-cyan-200">
                      Integration Status
                    </h3>
                    <p className="mt-2 text-sm leading-6 text-slate-300">
                      This page currently simulates integration states for the
                      frontend MVP. Real connection flows can be added during
                      backend integration.
                    </p>
                  </div>
                </div>
              </div>

              <div className="rounded-[2rem] border border-white/10 bg-white/[0.05] p-6 backdrop-blur-xl">
                <h2 className="text-2xl font-black">Recommended Setup</h2>

                <div className="mt-5 space-y-3 text-sm">
                  <div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/10 p-4 text-emerald-200">
                    Connect email import for incoming invoices.
                  </div>

                  <div className="rounded-2xl border border-cyan-400/20 bg-cyan-400/10 p-4 text-cyan-200">
                    Connect cloud storage for archived documents.
                  </div>

                  <div className="rounded-2xl border border-yellow-400/20 bg-yellow-400/10 p-4 text-yellow-200">
                    Connect accounting export after approval workflow is active.
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </main>
  );
}