"use client";

import {
  AlertTriangle,
  ArrowLeft,
  CheckCircle2,
  Download,
  Eye,
  FileText,
  Search,
  ShieldCheck,
} from "lucide-react";

const reports = [
  {
    id: "RPT-9001",
    invoice: "INV-2048",
    vendor: "Orion Business Supplies",
    date: "04 June 2026",
    score: "72%",
    risk: "High Risk",
    issues: 4,
    amount: "₹61,360",
  },
  {
    id: "RPT-9002",
    invoice: "INV-1025",
    vendor: "Metro Logistics",
    date: "03 June 2026",
    score: "84%",
    risk: "Warning",
    issues: 2,
    amount: "₹22,900",
  },
  {
    id: "RPT-9003",
    invoice: "INV-1024",
    vendor: "BrightEdge Supplies",
    date: "02 June 2026",
    score: "98%",
    risk: "Clean",
    issues: 0,
    amount: "₹48,500",
  },
  {
    id: "RPT-9004",
    invoice: "INV-1027",
    vendor: "Apex Office Mart",
    date: "01 June 2026",
    score: "96%",
    risk: "Clean",
    issues: 1,
    amount: "₹12,840",
  },
];

function riskClass(risk: string) {
  if (risk === "High Risk") return "bg-red-400/10 text-red-300 border-red-400/20";
  if (risk === "Warning") return "bg-yellow-400/10 text-yellow-300 border-yellow-400/20";
  return "bg-emerald-400/10 text-emerald-300 border-emerald-400/20";
}

export default function ReportsPage() {
  function downloadReport(report: (typeof reports)[number]) {
    const content = `
AuditFlow AI - Saved Audit Report

Report ID: ${report.id}
Invoice Number: ${report.invoice}
Vendor: ${report.vendor}
Date: ${report.date}
Amount: ${report.amount}
Compliance Score: ${report.score}
Risk Level: ${report.risk}
Issues Found: ${report.issues}

Summary:
This is a mock saved report generated for the AuditFlow AI MVP. In Version 2, this report will come from real OCR extraction, Gemini AI analysis, and database storage.

Generated by AuditFlow AI
`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = `${report.id}-audit-report.txt`;
    link.click();

    URL.revokeObjectURL(url);
  }

  return (
    <main className="min-h-screen bg-slate-950 px-6 py-6 text-white">
      <div className="absolute inset-0 -z-0 bg-[radial-gradient(circle_at_top_left,_rgba(34,211,238,0.18),_transparent_35%),radial-gradient(circle_at_bottom_right,_rgba(168,85,247,0.18),_transparent_35%)]" />

      <div className="relative z-10 mx-auto max-w-7xl">
        <nav className="flex items-center justify-between rounded-3xl border border-white/10 bg-white/[0.04] px-5 py-4 backdrop-blur-xl">
          <a
            href="/dashboard"
            className="flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-sm text-slate-300 hover:bg-white/5 hover:text-white"
          >
            <ArrowLeft size={16} />
            Dashboard
          </a>

          <div className="text-center">
            <p className="text-lg font-black">AuditFlow AI</p>
            <p className="text-xs text-slate-400">Audit Report Library</p>
          </div>

          <a
            href="/audit"
            className="rounded-full bg-cyan-400 px-5 py-2 text-sm font-bold text-slate-950 hover:bg-cyan-300"
          >
            New Audit
          </a>
        </nav>

        <section className="pt-10">
          <div className="grid gap-6 lg:grid-cols-[1fr_0.55fr]">
            <div>
              <div className="mb-6 inline-flex rounded-full border border-cyan-400/30 bg-cyan-400/10 px-4 py-2 text-sm text-cyan-200">
                Saved audit history
              </div>

              <h1 className="max-w-4xl text-5xl font-black tracking-tight md:text-6xl">
                Reports that keep every invoice accountable.
              </h1>

              <p className="mt-5 max-w-2xl leading-7 text-slate-400">
                View saved compliance reports, inspect risk levels, and download
                invoice audit summaries for review or submission.
              </p>
            </div>

            <div className="grid gap-4 sm:grid-cols-3 lg:grid-cols-1">
              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <ShieldCheck className="text-cyan-300" />
                <p className="mt-4 text-3xl font-black">4</p>
                <p className="text-sm text-slate-400">Reports saved</p>
              </div>

              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <AlertTriangle className="text-yellow-300" />
                <p className="mt-4 text-3xl font-black">7</p>
                <p className="text-sm text-slate-400">Issues tracked</p>
              </div>

              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <CheckCircle2 className="text-emerald-300" />
                <p className="mt-4 text-3xl font-black">2</p>
                <p className="text-sm text-slate-400">Clean documents</p>
              </div>
            </div>
          </div>

          <div className="mt-8 rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
            <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center">
              <div>
                <h2 className="text-2xl font-black">Audit Reports</h2>
                <p className="mt-1 text-sm text-slate-400">
                  Mock report records for the MVP dashboard.
                </p>
              </div>

              <div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-slate-950/70 px-4 py-3">
                <Search size={18} className="text-slate-400" />
                <input
                  placeholder="Search reports..."
                  className="bg-transparent text-sm outline-none placeholder:text-slate-500"
                />
              </div>
            </div>

            <div className="mt-6 grid gap-4">
              {reports.map((report) => (
                <div
                  key={report.id}
                  className="grid gap-4 rounded-3xl border border-white/10 bg-slate-900/70 p-5 md:grid-cols-[1fr_auto] md:items-center"
                >
                  <div className="flex gap-4">
                    <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-cyan-400/10 text-cyan-300">
                      <FileText size={26} />
                    </div>

                    <div>
                      <div className="flex flex-wrap items-center gap-3">
                        <h3 className="text-xl font-black">{report.id}</h3>
                        <span
                          className={`rounded-full border px-3 py-1 text-xs font-bold ${riskClass(
                            report.risk
                          )}`}
                        >
                          {report.risk}
                        </span>
                      </div>

                      <p className="mt-2 text-sm text-slate-400">
                        {report.invoice} · {report.vendor} · {report.date}
                      </p>

                      <div className="mt-4 grid gap-3 sm:grid-cols-3">
                        <div>
                          <p className="text-xs text-slate-500">Amount</p>
                          <p className="font-bold">{report.amount}</p>
                        </div>
                        <div>
                          <p className="text-xs text-slate-500">Score</p>
                          <p className="font-bold text-cyan-300">{report.score}</p>
                        </div>
                        <div>
                          <p className="text-xs text-slate-500">Issues</p>
                          <p className="font-bold">{report.issues}</p>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="flex flex-col gap-3 sm:flex-row md:flex-col">
                    <button className="flex items-center justify-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-5 py-3 text-sm font-bold text-white hover:bg-white/10">
                      <Eye size={17} />
                      View
                    </button>

                    <button
                      onClick={() => downloadReport(report)}
                      className="flex items-center justify-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-slate-950 hover:bg-cyan-200"
                    >
                      <Download size={17} />
                      Download
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
      </div>
    </main>
  );
}