"use client";

import { useState } from "react";
import {
  ArrowLeft,
  Ban,
  CheckCircle2,
  Clock,
  Download,
  FileText,
  IndianRupee,
  PauseCircle,
  ShieldCheck,
  XCircle,
} from "lucide-react";

type ApprovalStatus = "Pending" | "Approved" | "On Hold" | "Rejected";
type RiskLevel = "Low" | "Medium" | "High";
type Filter = "All" | ApprovalStatus;

type ApprovalItem = {
  id: string;
  invoice: string;
  vendor: string;
  amount: string;
  date: string;
  risk: RiskLevel;
  score: string;
  status: ApprovalStatus;
  note: string;
};

const initialApprovals: ApprovalItem[] = [
  {
    id: "APR-301",
    invoice: "INV-2048",
    vendor: "Orion Business Supplies",
    amount: "₹61,360",
    date: "04 June 2026",
    risk: "High",
    score: "72%",
    status: "Pending",
    note: "Missing GSTIN. Requires correction before payment.",
  },
  {
    id: "APR-302",
    invoice: "INV-1025",
    vendor: "Metro Logistics",
    amount: "₹22,900",
    date: "03 June 2026",
    risk: "Medium",
    score: "84%",
    status: "On Hold",
    note: "Possible duplicate pattern found. Needs verification.",
  },
  {
    id: "APR-303",
    invoice: "INV-1024",
    vendor: "BrightEdge Supplies",
    amount: "₹48,500",
    date: "02 June 2026",
    risk: "Low",
    score: "98%",
    status: "Approved",
    note: "Invoice passed compliance checks.",
  },
  {
    id: "APR-304",
    invoice: "INV-1027",
    vendor: "Apex Office Mart",
    amount: "₹12,840",
    date: "01 June 2026",
    risk: "Low",
    score: "96%",
    status: "Pending",
    note: "Minor field issue detected. Review before approval.",
  },
];

function statusClass(status: ApprovalStatus) {
  if (status === "Approved") {
    return "border-emerald-400/20 bg-emerald-400/10 text-emerald-300";
  }

  if (status === "On Hold") {
    return "border-yellow-400/20 bg-yellow-400/10 text-yellow-300";
  }

  if (status === "Rejected") {
    return "border-red-400/20 bg-red-400/10 text-red-300";
  }

  return "border-cyan-400/20 bg-cyan-400/10 text-cyan-300";
}

function riskClass(risk: RiskLevel) {
  if (risk === "High") {
    return "border-red-400/20 bg-red-400/10 text-red-300";
  }

  if (risk === "Medium") {
    return "border-yellow-400/20 bg-yellow-400/10 text-yellow-300";
  }

  return "border-emerald-400/20 bg-emerald-400/10 text-emerald-300";
}

export default function ApprovalsPage() {
  const [approvals, setApprovals] = useState<ApprovalItem[]>(initialApprovals);
  const [filter, setFilter] = useState<Filter>("All");

  const filters: Filter[] = ["All", "Pending", "Approved", "On Hold", "Rejected"];

  const filteredApprovals = approvals.filter((item) => {
    if (filter === "All") return true;
    return item.status === filter;
  });

  const pendingCount = approvals.filter((item) => item.status === "Pending").length;
  const approvedCount = approvals.filter((item) => item.status === "Approved").length;
  const holdCount = approvals.filter((item) => item.status === "On Hold").length;

  function updateStatus(id: string, status: ApprovalStatus) {
    setApprovals((currentItems) =>
      currentItems.map((item) =>
        item.id === id ? { ...item, status } : item
      )
    );
  }

  function downloadApprovalSummary() {
    const content = `
AuditFlow AI - Payment Approval Summary

${approvals
  .map(
    (item) =>
      `${item.id}
Invoice: ${item.invoice}
Vendor: ${item.vendor}
Amount: ${item.amount}
Date: ${item.date}
Risk Level: ${item.risk}
Compliance Score: ${item.score}
Status: ${item.status}
Note: ${item.note}`
  )
  .join("\n\n")}

Generated by AuditFlow AI
`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const link = window.document.createElement("a");
    link.href = url;
    link.download = "auditflow-ai-payment-approvals.txt";
    link.click();

    URL.revokeObjectURL(url);
  }

  return (
    <main className="min-h-screen bg-slate-950 px-6 py-6 text-white">
      <div className="absolute inset-0 -z-0 bg-[radial-gradient(circle_at_top_left,_rgba(34,211,238,0.18),_transparent_35%),radial-gradient(circle_at_bottom_right,_rgba(34,197,94,0.14),_transparent_35%)]" />

      <div className="relative z-10 mx-auto max-w-7xl">
        <nav className="flex items-center justify-between rounded-3xl border border-white/10 bg-white/[0.04] px-5 py-4 backdrop-blur-xl">
          <a
            href="/dashboard"
            className="flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-sm text-slate-300 hover:bg-white/5 hover:text-white"
          >
            <ArrowLeft size={16} />
            Dashboard
          </a>

          <div className="text-center">
            <p className="text-lg font-black">AuditFlow AI</p>
            <p className="text-xs text-slate-400">Payment Approvals</p>
          </div>

          <button
            onClick={downloadApprovalSummary}
            className="flex items-center gap-2 rounded-full bg-cyan-400 px-5 py-2 text-sm font-bold text-slate-950 hover:bg-cyan-300"
          >
            <Download size={17} />
            Export
          </button>
        </nav>

        <section className="pt-10">
          <div className="grid gap-6 lg:grid-cols-[1fr_0.55fr]">
            <div>
              <div className="mb-6 inline-flex rounded-full border border-emerald-400/30 bg-emerald-400/10 px-4 py-2 text-sm text-emerald-200">
                Payment control workflow
              </div>

              <h1 className="max-w-4xl text-5xl font-black tracking-tight md:text-6xl">
                Approve invoices only after risk checks.
              </h1>

              <p className="mt-5 max-w-2xl leading-7 text-slate-400">
                Review audited invoices, hold risky payments, reject invalid
                documents, and approve clean invoices for payment processing.
              </p>
            </div>

            <div className="grid gap-4 sm:grid-cols-3 lg:grid-cols-1">
              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <Clock className="text-cyan-300" />
                <p className="mt-4 text-3xl font-black">{pendingCount}</p>
                <p className="text-sm text-slate-400">Pending approvals</p>
              </div>

              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <CheckCircle2 className="text-emerald-300" />
                <p className="mt-4 text-3xl font-black">{approvedCount}</p>
                <p className="text-sm text-slate-400">Approved invoices</p>
              </div>

              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <PauseCircle className="text-yellow-300" />
                <p className="mt-4 text-3xl font-black">{holdCount}</p>
                <p className="text-sm text-slate-400">Invoices on hold</p>
              </div>
            </div>
          </div>

          <div className="mt-8 rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
            <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center">
              <div>
                <h2 className="text-2xl font-black">Approval Queue</h2>
                <p className="mt-1 text-sm text-slate-400">
                  Update payment decisions based on invoice audit results.
                </p>
              </div>

              <div className="flex flex-wrap gap-2">
                {filters.map((item) => (
                  <button
                    key={item}
                    onClick={() => setFilter(item)}
                    className={`rounded-full px-4 py-2 text-sm font-bold transition ${
                      filter === item
                        ? "bg-cyan-400 text-slate-950"
                        : "border border-white/10 bg-white/[0.04] text-slate-400 hover:bg-white/10 hover:text-white"
                    }`}
                  >
                    {item}
                  </button>
                ))}
              </div>
            </div>

            <div className="mt-6 grid gap-4">
              {filteredApprovals.map((item) => (
                <div
                  key={item.id}
                  className="rounded-3xl border border-white/10 bg-slate-900/70 p-5"
                >
                  <div className="grid gap-5 xl:grid-cols-[1fr_auto] xl:items-center">
                    <div className="flex gap-4">
                      <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-cyan-400/10 text-cyan-300">
                        <FileText size={26} />
                      </div>

                      <div>
                        <div className="flex flex-wrap items-center gap-3">
                          <h3 className="text-xl font-black">{item.invoice}</h3>

                          <span
                            className={`rounded-full border px-3 py-1 text-xs font-bold ${statusClass(
                              item.status
                            )}`}
                          >
                            {item.status}
                          </span>

                          <span
                            className={`rounded-full border px-3 py-1 text-xs font-bold ${riskClass(
                              item.risk
                            )}`}
                          >
                            {item.risk} Risk
                          </span>
                        </div>

                        <p className="mt-2 text-sm text-slate-400">
                          {item.id} · {item.vendor} · {item.date}
                        </p>

                        <div className="mt-4 grid gap-3 sm:grid-cols-3">
                          <div>
                            <p className="text-xs text-slate-500">Amount</p>
                            <p className="flex items-center gap-1 font-bold">
                              <IndianRupee size={15} />
                              {item.amount.replace("₹", "")}
                            </p>
                          </div>

                          <div>
                            <p className="text-xs text-slate-500">Score</p>
                            <p className="font-bold text-cyan-300">
                              {item.score}
                            </p>
                          </div>

                          <div>
                            <p className="text-xs text-slate-500">Audit note</p>
                            <p className="text-sm font-bold text-slate-300">
                              {item.note}
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-1">
                      <button
                        onClick={() => updateStatus(item.id, "Approved")}
                        className="flex items-center justify-center gap-2 rounded-full bg-emerald-400 px-5 py-3 text-sm font-bold text-slate-950 hover:bg-emerald-300"
                      >
                        <CheckCircle2 size={17} />
                        Approve
                      </button>

                      <button
                        onClick={() => updateStatus(item.id, "On Hold")}
                        className="flex items-center justify-center gap-2 rounded-full border border-yellow-400/20 bg-yellow-400/10 px-5 py-3 text-sm font-bold text-yellow-300 hover:bg-yellow-400/20"
                      >
                        <PauseCircle size={17} />
                        Hold
                      </button>

                      <button
                        onClick={() => updateStatus(item.id, "Rejected")}
                        className="flex items-center justify-center gap-2 rounded-full border border-red-400/20 bg-red-400/10 px-5 py-3 text-sm font-bold text-red-300 hover:bg-red-400/20"
                      >
                        <XCircle size={17} />
                        Reject
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {filteredApprovals.length === 0 && (
              <div className="mt-6 rounded-3xl border border-white/10 bg-slate-900/70 p-10 text-center">
                <Ban className="mx-auto text-cyan-300" size={48} />
                <h3 className="mt-4 text-2xl font-black">No invoices found</h3>
                <p className="mt-2 text-sm text-slate-400">
                  There are no payment approvals matching this filter.
                </p>
              </div>
            )}
          </div>

          <div className="mt-8 rounded-3xl border border-cyan-400/20 bg-cyan-400/10 p-5">
            <div className="flex gap-3">
              <ShieldCheck className="mt-1 shrink-0 text-cyan-300" size={22} />
              <div>
                <h3 className="font-black text-cyan-200">
                  Approval Control
                </h3>
                <p className="mt-2 text-sm leading-6 text-slate-300">
                  Payment approvals should depend on audit score, risk level,
                  required tax fields, duplicate checks, and manual review
                  outcome.
                </p>
              </div>
            </div>
          </div>
        </section>
      </div>
    </main>
  );
}