"use client";

import { useState } from "react";
import {
  AlertTriangle,
  ArrowLeft,
  CheckCircle2,
  Download,
  FileText,
  Loader2,
  ShieldAlert,
  UploadCloud,
} from "lucide-react";

type BatchStatus = "Clean" | "Warning" | "High Risk";

type BatchResult = {
  id: string;
  fileName: string;
  vendor: string;
  invoice: string;
  amount: string;
  score: string;
  issues: number;
  status: BatchStatus;
};

const mockResults: BatchResult[] = [
  {
    id: "BAT-001",
    fileName: "invoice-orion-2048.pdf",
    vendor: "Orion Business Supplies",
    invoice: "INV-2048",
    amount: "₹61,360",
    score: "72%",
    issues: 4,
    status: "High Risk",
  },
  {
    id: "BAT-002",
    fileName: "metro-logistics-receipt.png",
    vendor: "Metro Logistics",
    invoice: "INV-1025",
    amount: "₹22,900",
    score: "84%",
    issues: 2,
    status: "Warning",
  },
  {
    id: "BAT-003",
    fileName: "brightedge-tax-invoice.pdf",
    vendor: "BrightEdge Supplies",
    invoice: "INV-1024",
    amount: "₹48,500",
    score: "98%",
    issues: 0,
    status: "Clean",
  },
  {
    id: "BAT-004",
    fileName: "apex-office-mart-bill.jpg",
    vendor: "Apex Office Mart",
    invoice: "INV-1027",
    amount: "₹12,840",
    score: "96%",
    issues: 1,
    status: "Clean",
  },
];

function statusClass(status: BatchStatus) {
  if (status === "Clean") {
    return "border-emerald-400/20 bg-emerald-400/10 text-emerald-300";
  }

  if (status === "Warning") {
    return "border-yellow-400/20 bg-yellow-400/10 text-yellow-300";
  }

  return "border-red-400/20 bg-red-400/10 text-red-300";
}

export default function BatchAuditPage() {
  const [selectedFiles, setSelectedFiles] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [processed, setProcessed] = useState(false);

  const cleanCount = mockResults.filter((item) => item.status === "Clean").length;
  const warningCount = mockResults.filter(
    (item) => item.status === "Warning"
  ).length;
  const highRiskCount = mockResults.filter(
    (item) => item.status === "High Risk"
  ).length;

  function handleFiles(files: FileList | null) {
    if (!files) return;

    const names = Array.from(files).map((file) => file.name);
    setSelectedFiles(names);
    setProcessed(false);
  }

  function runBatchAudit() {
    setLoading(true);
    setProcessed(false);

    setTimeout(() => {
      setLoading(false);
      setProcessed(true);
    }, 1800);
  }

  function downloadBatchSummary() {
    const content = `
AuditFlow AI - Batch Audit Summary

Documents Processed: ${mockResults.length}
Clean Documents: ${cleanCount}
Warning Documents: ${warningCount}
High Risk Documents: ${highRiskCount}

Results:
${mockResults
  .map(
    (item) =>
      `${item.id}
File: ${item.fileName}
Invoice: ${item.invoice}
Vendor: ${item.vendor}
Amount: ${item.amount}
Compliance Score: ${item.score}
Issues: ${item.issues}
Status: ${item.status}`
  )
  .join("\n\n")}

Generated by AuditFlow AI
`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const link = window.document.createElement("a");
    link.href = url;
    link.download = "auditflow-ai-batch-summary.txt";
    link.click();

    URL.revokeObjectURL(url);
  }

  return (
    <main className="min-h-screen bg-slate-950 px-6 py-6 text-white">
      <div className="absolute inset-0 -z-0 bg-[radial-gradient(circle_at_top_left,_rgba(34,211,238,0.18),_transparent_35%),radial-gradient(circle_at_bottom_right,_rgba(239,68,68,0.15),_transparent_35%)]" />

      <div className="relative z-10 mx-auto max-w-7xl">
        <nav className="flex items-center justify-between rounded-3xl border border-white/10 bg-white/[0.04] px-5 py-4 backdrop-blur-xl">
          <a
            href="/dashboard"
            className="flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-sm text-slate-300 hover:bg-white/5 hover:text-white"
          >
            <ArrowLeft size={16} />
            Dashboard
          </a>

          <div className="text-center">
            <p className="text-lg font-black">AuditFlow AI</p>
            <p className="text-xs text-slate-400">Batch Audit</p>
          </div>

          <a
            href="/audit"
            className="rounded-full bg-cyan-400 px-5 py-2 text-sm font-bold text-slate-950 hover:bg-cyan-300"
          >
            Single Audit
          </a>
        </nav>

        <section className="grid gap-8 pt-10 lg:grid-cols-[0.85fr_1.15fr]">
          <div>
            <div className="mb-6 inline-flex rounded-full border border-cyan-400/30 bg-cyan-400/10 px-4 py-2 text-sm text-cyan-200">
              Multi-document processing
            </div>

            <h1 className="max-w-4xl text-5xl font-black tracking-tight md:text-6xl">
              Audit multiple invoices in one batch.
            </h1>

            <p className="mt-5 max-w-2xl leading-7 text-slate-400">
              Upload multiple invoices, receipts, or tax documents together and
              review a consolidated risk summary after processing.
            </p>

            <label className="mt-8 flex cursor-pointer flex-col items-center justify-center rounded-[2rem] border border-dashed border-cyan-400/40 bg-cyan-400/5 p-10 text-center transition hover:bg-cyan-400/10">
              <input
                type="file"
                multiple
                accept=".pdf,.png,.jpg,.jpeg"
                className="hidden"
                onChange={(event) => handleFiles(event.target.files)}
              />

              <UploadCloud size={56} className="text-cyan-300" />

              <p className="mt-5 text-2xl font-black">
                Choose multiple documents
              </p>

              <p className="mt-2 text-sm text-slate-400">
                PDF, PNG, JPG, and JPEG supported
              </p>
            </label>

            <div className="mt-6 rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
              <h2 className="text-xl font-black">Selected Files</h2>

              {selectedFiles.length === 0 ? (
                <p className="mt-3 text-sm text-slate-400">
                  No files selected yet.
                </p>
              ) : (
                <div className="mt-4 space-y-3">
                  {selectedFiles.map((fileName) => (
                    <div
                      key={fileName}
                      className="flex items-center gap-3 rounded-2xl border border-white/10 bg-slate-900/70 p-4"
                    >
                      <FileText size={18} className="text-cyan-300" />
                      <p className="text-sm font-bold text-slate-300">
                        {fileName}
                      </p>
                    </div>
                  ))}
                </div>
              )}
            </div>

            <button
              onClick={runBatchAudit}
              disabled={loading || selectedFiles.length === 0}
              className="mt-6 flex w-full items-center justify-center gap-3 rounded-full bg-cyan-400 px-8 py-4 font-black text-slate-950 transition hover:scale-[1.02] hover:bg-cyan-300 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {loading && <Loader2 className="animate-spin" size={20} />}
              {loading ? "Processing Batch..." : "Run Batch Audit"}
            </button>
          </div>

          <div className="rounded-[2rem] border border-white/10 bg-white/[0.05] p-6 backdrop-blur-xl">
            {!loading && !processed && (
              <div className="flex min-h-[620px] flex-col items-center justify-center text-center">
                <div className="rounded-full border border-white/10 bg-white/[0.04] p-8">
                  <UploadCloud size={72} className="text-slate-400" />
                </div>

                <h2 className="mt-6 text-3xl font-black">
                  Batch results waiting
                </h2>

                <p className="mt-3 max-w-md text-slate-400">
                  Select multiple files and run a batch audit. Risk summary and
                  document-level results will appear here.
                </p>
              </div>
            )}

            {loading && (
              <div className="flex min-h-[620px] flex-col items-center justify-center text-center">
                <Loader2 size={72} className="animate-spin text-cyan-300" />

                <h2 className="mt-6 text-3xl font-black">
                  Auditing batch...
                </h2>

                <p className="mt-3 max-w-md text-slate-400">
                  Checking documents for missing fields, duplicate risks, and
                  tax compliance issues.
                </p>
              </div>
            )}

            {processed && (
              <div>
                <div className="grid gap-4 sm:grid-cols-3">
                  <div className="rounded-3xl border border-white/10 bg-slate-900/70 p-5">
                    <CheckCircle2 className="text-emerald-300" />
                    <p className="mt-4 text-3xl font-black">{cleanCount}</p>
                    <p className="text-sm text-slate-400">Clean documents</p>
                  </div>

                  <div className="rounded-3xl border border-white/10 bg-slate-900/70 p-5">
                    <AlertTriangle className="text-yellow-300" />
                    <p className="mt-4 text-3xl font-black">{warningCount}</p>
                    <p className="text-sm text-slate-400">Warnings</p>
                  </div>

                  <div className="rounded-3xl border border-white/10 bg-slate-900/70 p-5">
                    <ShieldAlert className="text-red-300" />
                    <p className="mt-4 text-3xl font-black">{highRiskCount}</p>
                    <p className="text-sm text-slate-400">High risk</p>
                  </div>
                </div>

                <div className="mt-6 flex flex-col justify-between gap-4 md:flex-row md:items-center">
                  <div>
                    <h2 className="text-2xl font-black">Batch Results</h2>
                    <p className="mt-1 text-sm text-slate-400">
                      Mock batch results for selected documents.
                    </p>
                  </div>

                  <button
                    onClick={downloadBatchSummary}
                    className="flex items-center justify-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-slate-950 hover:bg-cyan-200"
                  >
                    <Download size={17} />
                    Download Summary
                  </button>
                </div>

                <div className="mt-6 overflow-x-auto">
                  <table className="w-full min-w-[820px] border-separate border-spacing-y-3 text-left">
                    <thead className="text-sm text-slate-500">
                      <tr>
                        <th className="px-4">File</th>
                        <th className="px-4">Vendor</th>
                        <th className="px-4">Invoice</th>
                        <th className="px-4">Amount</th>
                        <th className="px-4">Score</th>
                        <th className="px-4">Issues</th>
                        <th className="px-4">Status</th>
                      </tr>
                    </thead>

                    <tbody>
                      {mockResults.map((item) => (
                        <tr key={item.id} className="bg-slate-900/70 text-sm">
                          <td className="rounded-l-2xl px-4 py-4 font-bold">
                            {item.fileName}
                          </td>

                          <td className="px-4 py-4 text-slate-300">
                            {item.vendor}
                          </td>

                          <td className="px-4 py-4 text-slate-400">
                            {item.invoice}
                          </td>

                          <td className="px-4 py-4 font-bold">
                            {item.amount}
                          </td>

                          <td className="px-4 py-4 font-bold text-cyan-300">
                            {item.score}
                          </td>

                          <td className="px-4 py-4 font-bold">
                            {item.issues}
                          </td>

                          <td className="rounded-r-2xl px-4 py-4">
                            <span
                              className={`rounded-full border px-3 py-1 text-xs font-bold ${statusClass(
                                item.status
                              )}`}
                            >
                              {item.status}
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

                <div className="mt-6 rounded-3xl border border-cyan-400/20 bg-cyan-400/10 p-5">
                  <h3 className="font-black text-cyan-200">
                    Batch Recommendation
                  </h3>
                  <p className="mt-2 text-sm leading-6 text-slate-300">
                    Review high-risk documents first, then verify warning items
                    before payment approval or tax submission.
                  </p>
                </div>
              </div>
            )}
          </div>
        </section>
      </div>
    </main>
  );
}