"use client";

import { useState } from "react";
import {
  AlertTriangle,
  ArrowLeft,
  CheckCircle2,
  Download,
  Eye,
  FileText,
  FolderOpen,
  RefreshCw,
  Search,
  ShieldAlert,
  UploadCloud,
} from "lucide-react";

type DocumentStatus = "Clean" | "Warning" | "High Risk" | "Archived";
type Filter = "All" | "Clean" | "Warning" | "High Risk" | "Archived";

type DocumentItem = {
  id: string;
  name: string;
  type: string;
  vendor: string;
  uploaded: string;
  amount: string;
  score: string;
  issues: number;
  status: DocumentStatus;
};

const initialDocuments: DocumentItem[] = [
  {
    id: "DOC-1001",
    name: "invoice-orion-2048.pdf",
    type: "GST Invoice",
    vendor: "Orion Business Supplies",
    uploaded: "04 June 2026",
    amount: "₹61,360",
    score: "72%",
    issues: 4,
    status: "High Risk",
  },
  {
    id: "DOC-1002",
    name: "metro-logistics-receipt.png",
    type: "Receipt",
    vendor: "Metro Logistics",
    uploaded: "03 June 2026",
    amount: "₹22,900",
    score: "84%",
    issues: 2,
    status: "Warning",
  },
  {
    id: "DOC-1003",
    name: "brightedge-tax-invoice.pdf",
    type: "Tax Invoice",
    vendor: "BrightEdge Supplies",
    uploaded: "02 June 2026",
    amount: "₹48,500",
    score: "98%",
    issues: 0,
    status: "Clean",
  },
  {
    id: "DOC-1004",
    name: "apex-office-mart-bill.jpg",
    type: "Purchase Bill",
    vendor: "Apex Office Mart",
    uploaded: "01 June 2026",
    amount: "₹12,840",
    score: "96%",
    issues: 1,
    status: "Clean",
  },
  {
    id: "DOC-1005",
    name: "nova-tech-services-invoice.pdf",
    type: "Service Invoice",
    vendor: "Nova Tech Services",
    uploaded: "31 May 2026",
    amount: "₹76,200",
    score: "78%",
    issues: 3,
    status: "Warning",
  },
];

function statusClass(status: DocumentStatus) {
  if (status === "Clean") {
    return "border-emerald-400/20 bg-emerald-400/10 text-emerald-300";
  }

  if (status === "Warning") {
    return "border-yellow-400/20 bg-yellow-400/10 text-yellow-300";
  }

  if (status === "High Risk") {
    return "border-red-400/20 bg-red-400/10 text-red-300";
  }

  return "border-slate-400/20 bg-slate-400/10 text-slate-300";
}

export default function DocumentsPage() {
  const [documents, setDocuments] = useState<DocumentItem[]>(initialDocuments);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState<Filter>("All");

  const filters: Filter[] = ["All", "Clean", "Warning", "High Risk", "Archived"];

  const filteredDocuments = documents.filter((doc) => {
    const matchesSearch =
      doc.name.toLowerCase().includes(search.toLowerCase()) ||
      doc.vendor.toLowerCase().includes(search.toLowerCase()) ||
      doc.id.toLowerCase().includes(search.toLowerCase());

    const matchesFilter = filter === "All" || doc.status === filter;

    return matchesSearch && matchesFilter;
  });

  const cleanCount = documents.filter((doc) => doc.status === "Clean").length;
  const warningCount = documents.filter((doc) => doc.status === "Warning").length;
  const highRiskCount = documents.filter((doc) => doc.status === "High Risk").length;

  function archiveDocument(id: string) {
    setDocuments((currentDocuments) =>
      currentDocuments.map((doc) =>
        doc.id === id ? { ...doc, status: "Archived" } : doc
      )
    );
  }

  function restoreDocument(id: string) {
    setDocuments((currentDocuments) =>
      currentDocuments.map((doc) =>
        doc.id === id ? { ...doc, status: "Warning" } : doc
      )
    );
  }

  function downloadSummary(doc: DocumentItem) {
    const content = `
AuditFlow AI - Document Summary

Document ID: ${doc.id}
File Name: ${doc.name}
Document Type: ${doc.type}
Vendor: ${doc.vendor}
Uploaded: ${doc.uploaded}
Amount: ${doc.amount}
Compliance Score: ${doc.score}
Issues Found: ${doc.issues}
Status: ${doc.status}

Generated by AuditFlow AI
`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const link = window.document.createElement("a");
    link.href = url;
    link.download = `${doc.id}-summary.txt`;
    link.click();

    URL.revokeObjectURL(url);
  }

  return (
    <main className="min-h-screen bg-slate-950 px-6 py-6 text-white">
      <div className="absolute inset-0 -z-0 bg-[radial-gradient(circle_at_top_left,_rgba(34,211,238,0.18),_transparent_35%),radial-gradient(circle_at_bottom_right,_rgba(168,85,247,0.16),_transparent_35%)]" />

      <div className="relative z-10 mx-auto max-w-7xl">
        <nav className="flex items-center justify-between rounded-3xl border border-white/10 bg-white/[0.04] px-5 py-4 backdrop-blur-xl">
          <a
            href="/dashboard"
            className="flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-sm text-slate-300 hover:bg-white/5 hover:text-white"
          >
            <ArrowLeft size={16} />
            Dashboard
          </a>

          <div className="text-center">
            <p className="text-lg font-black">AuditFlow AI</p>
            <p className="text-xs text-slate-400">Document Vault</p>
          </div>

          <a
            href="/audit"
            className="rounded-full bg-cyan-400 px-5 py-2 text-sm font-bold text-slate-950 hover:bg-cyan-300"
          >
            Upload Document
          </a>
        </nav>

        <section className="pt-10">
          <div className="grid gap-6 lg:grid-cols-[1fr_0.55fr]">
            <div>
              <div className="mb-6 inline-flex rounded-full border border-cyan-400/30 bg-cyan-400/10 px-4 py-2 text-sm text-cyan-200">
                Uploaded document library
              </div>

              <h1 className="max-w-4xl text-5xl font-black tracking-tight md:text-6xl">
                Store and track every audited invoice.
              </h1>

              <p className="mt-5 max-w-2xl leading-7 text-slate-400">
                View uploaded invoices, receipts, and tax documents with audit
                scores, issue counts, risk status, and downloadable summaries.
              </p>
            </div>

            <div className="grid gap-4 sm:grid-cols-3 lg:grid-cols-1">
              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <CheckCircle2 className="text-emerald-300" />
                <p className="mt-4 text-3xl font-black">{cleanCount}</p>
                <p className="text-sm text-slate-400">Clean documents</p>
              </div>

              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <AlertTriangle className="text-yellow-300" />
                <p className="mt-4 text-3xl font-black">{warningCount}</p>
                <p className="text-sm text-slate-400">Warning documents</p>
              </div>

              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <ShieldAlert className="text-red-300" />
                <p className="mt-4 text-3xl font-black">{highRiskCount}</p>
                <p className="text-sm text-slate-400">High-risk documents</p>
              </div>
            </div>
          </div>

          <div className="mt-8 rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
            <div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-center">
              <div>
                <h2 className="text-2xl font-black">Documents</h2>
                <p className="mt-1 text-sm text-slate-400">
                  Mock document records for the MVP system.
                </p>
              </div>

              <div className="flex flex-col gap-3 md:flex-row md:items-center">
                <div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-slate-950/70 px-4 py-3">
                  <Search size={18} className="text-slate-400" />
                  <input
                    value={search}
                    onChange={(event) => setSearch(event.target.value)}
                    placeholder="Search documents..."
                    className="bg-transparent text-sm outline-none placeholder:text-slate-500"
                  />
                </div>

                <div className="flex flex-wrap gap-2">
                  {filters.map((item) => (
                    <button
                      key={item}
                      onClick={() => setFilter(item)}
                      className={`rounded-full px-4 py-2 text-sm font-bold transition ${
                        filter === item
                          ? "bg-cyan-400 text-slate-950"
                          : "border border-white/10 bg-white/[0.04] text-slate-400 hover:bg-white/10 hover:text-white"
                      }`}
                    >
                      {item}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            <div className="mt-6 grid gap-4">
              {filteredDocuments.map((doc) => (
                <div
                  key={doc.id}
                  className="grid gap-5 rounded-3xl border border-white/10 bg-slate-900/70 p-5 xl:grid-cols-[1fr_auto] xl:items-center"
                >
                  <div className="flex gap-4">
                    <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-cyan-400/10 text-cyan-300">
                      <FileText size={26} />
                    </div>

                    <div>
                      <div className="flex flex-wrap items-center gap-3">
                        <h3 className="text-xl font-black">{doc.name}</h3>

                        <span
                          className={`rounded-full border px-3 py-1 text-xs font-bold ${statusClass(
                            doc.status
                          )}`}
                        >
                          {doc.status}
                        </span>
                      </div>

                      <p className="mt-2 text-sm text-slate-400">
                        {doc.id} · {doc.vendor} · {doc.type}
                      </p>

                      <div className="mt-4 grid gap-3 sm:grid-cols-4">
                        <div>
                          <p className="text-xs text-slate-500">Uploaded</p>
                          <p className="font-bold">{doc.uploaded}</p>
                        </div>

                        <div>
                          <p className="text-xs text-slate-500">Amount</p>
                          <p className="font-bold">{doc.amount}</p>
                        </div>

                        <div>
                          <p className="text-xs text-slate-500">Score</p>
                          <p className="font-bold text-cyan-300">{doc.score}</p>
                        </div>

                        <div>
                          <p className="text-xs text-slate-500">Issues</p>
                          <p className="font-bold">{doc.issues}</p>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="grid gap-3 sm:grid-cols-3 xl:grid-cols-1">
                    <a
                      href="/reports"
                      className="flex items-center justify-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-5 py-3 text-sm font-bold text-white hover:bg-white/10"
                    >
                      <Eye size={17} />
                      View Report
                    </a>

                    <button
                      onClick={() => downloadSummary(doc)}
                      className="flex items-center justify-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-slate-950 hover:bg-cyan-200"
                    >
                      <Download size={17} />
                      Download
                    </button>

                    {doc.status === "Archived" ? (
                      <button
                        onClick={() => restoreDocument(doc.id)}
                        className="flex items-center justify-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-5 py-3 text-sm font-bold text-emerald-300 hover:bg-emerald-400/20"
                      >
                        <RefreshCw size={17} />
                        Restore
                      </button>
                    ) : (
                      <button
                        onClick={() => archiveDocument(doc.id)}
                        className="flex items-center justify-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-5 py-3 text-sm font-bold text-white hover:bg-white/10"
                      >
                        <FolderOpen size={17} />
                        Archive
                      </button>
                    )}
                  </div>
                </div>
              ))}
            </div>

            {filteredDocuments.length === 0 && (
              <div className="mt-6 rounded-3xl border border-white/10 bg-slate-900/70 p-10 text-center">
                <UploadCloud className="mx-auto text-cyan-300" size={48} />
                <h3 className="mt-4 text-2xl font-black">No documents found</h3>
                <p className="mt-2 text-sm text-slate-400">
                  Try changing the search term or filter.
                </p>
              </div>
            )}
          </div>
        </section>
      </div>
    </main>
  );
}