"use client";

import { useState } from "react";
import {
  AlertTriangle,
  ArrowLeft,
  CheckCircle2,
  Clock,
  Download,
  FileText,
  History,
  Search,
  Settings,
  ShieldCheck,
  UploadCloud,
  UserCheck,
} from "lucide-react";

type LogType =
  | "Upload"
  | "Audit"
  | "Report"
  | "Review"
  | "Settings"
  | "System";

type LogItem = {
  id: string;
  type: LogType;
  actor: string;
  action: string;
  target: string;
  time: string;
  status: "Success" | "Warning" | "High Risk";
};

const logs: LogItem[] = [
  {
    id: "LOG-7001",
    type: "Upload",
    actor: "Finance Manager",
    action: "Uploaded document",
    target: "invoice-orion-2048.pdf",
    time: "04 June 2026, 10:24 AM",
    status: "Success",
  },
  {
    id: "LOG-7002",
    type: "Audit",
    actor: "AuditFlow AI",
    action: "Detected missing GSTIN",
    target: "INV-2048",
    time: "04 June 2026, 10:25 AM",
    status: "High Risk",
  },
  {
    id: "LOG-7003",
    type: "Review",
    actor: "Finance Manager",
    action: "Requested correction",
    target: "Orion Business Supplies",
    time: "04 June 2026, 10:31 AM",
    status: "Warning",
  },
  {
    id: "LOG-7004",
    type: "Report",
    actor: "Finance Manager",
    action: "Downloaded audit report",
    target: "RPT-9001",
    time: "04 June 2026, 10:35 AM",
    status: "Success",
  },
  {
    id: "LOG-7005",
    type: "Settings",
    actor: "Admin",
    action: "Changed review threshold",
    target: "75% compliance threshold",
    time: "03 June 2026, 05:40 PM",
    status: "Success",
  },
  {
    id: "LOG-7006",
    type: "System",
    actor: "AuditFlow AI",
    action: "Moved invoice to review queue",
    target: "INV-1026",
    time: "03 June 2026, 02:18 PM",
    status: "High Risk",
  },
  {
    id: "LOG-7007",
    type: "Audit",
    actor: "AuditFlow AI",
    action: "Detected possible duplicate invoice",
    target: "Metro Logistics",
    time: "03 June 2026, 01:12 PM",
    status: "Warning",
  },
];

function statusClass(status: LogItem["status"]) {
  if (status === "Success") {
    return "border-emerald-400/20 bg-emerald-400/10 text-emerald-300";
  }

  if (status === "Warning") {
    return "border-yellow-400/20 bg-yellow-400/10 text-yellow-300";
  }

  return "border-red-400/20 bg-red-400/10 text-red-300";
}

function typeIcon(type: LogType) {
  if (type === "Upload") return UploadCloud;
  if (type === "Audit") return ShieldCheck;
  if (type === "Report") return FileText;
  if (type === "Review") return UserCheck;
  if (type === "Settings") return Settings;
  return History;
}

export default function AuditTrailPage() {
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState<LogType | "All">("All");

  const filters: Array<LogType | "All"> = [
    "All",
    "Upload",
    "Audit",
    "Report",
    "Review",
    "Settings",
    "System",
  ];

  const filteredLogs = logs.filter((log) => {
    const matchesFilter = filter === "All" || log.type === filter;

    const matchesSearch =
      log.id.toLowerCase().includes(search.toLowerCase()) ||
      log.actor.toLowerCase().includes(search.toLowerCase()) ||
      log.action.toLowerCase().includes(search.toLowerCase()) ||
      log.target.toLowerCase().includes(search.toLowerCase());

    return matchesFilter && matchesSearch;
  });

  const highRiskCount = logs.filter((log) => log.status === "High Risk").length;
  const warningCount = logs.filter((log) => log.status === "Warning").length;
  const successCount = logs.filter((log) => log.status === "Success").length;

  function downloadAuditTrail() {
    const content = `
AuditFlow AI - Audit Trail Export

${logs
  .map(
    (log) =>
      `${log.id}
Type: ${log.type}
Actor: ${log.actor}
Action: ${log.action}
Target: ${log.target}
Time: ${log.time}
Status: ${log.status}`
  )
  .join("\n\n")}

Generated by AuditFlow AI
`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const link = window.document.createElement("a");
    link.href = url;
    link.download = "auditflow-ai-audit-trail.txt";
    link.click();

    URL.revokeObjectURL(url);
  }

  return (
    <main className="min-h-screen bg-slate-950 px-6 py-6 text-white">
      <div className="absolute inset-0 -z-0 bg-[radial-gradient(circle_at_top_left,_rgba(34,211,238,0.18),_transparent_35%),radial-gradient(circle_at_bottom_right,_rgba(168,85,247,0.16),_transparent_35%)]" />

      <div className="relative z-10 mx-auto max-w-7xl">
        <nav className="flex items-center justify-between rounded-3xl border border-white/10 bg-white/[0.04] px-5 py-4 backdrop-blur-xl">
          <a
            href="/dashboard"
            className="flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-sm text-slate-300 hover:bg-white/5 hover:text-white"
          >
            <ArrowLeft size={16} />
            Dashboard
          </a>

          <div className="text-center">
            <p className="text-lg font-black">AuditFlow AI</p>
            <p className="text-xs text-slate-400">Audit Trail</p>
          </div>

          <button
            onClick={downloadAuditTrail}
            className="flex items-center gap-2 rounded-full bg-cyan-400 px-5 py-2 text-sm font-bold text-slate-950 hover:bg-cyan-300"
          >
            <Download size={17} />
            Export
          </button>
        </nav>

        <section className="pt-10">
          <div className="grid gap-6 lg:grid-cols-[1fr_0.55fr]">
            <div>
              <div className="mb-6 inline-flex rounded-full border border-cyan-400/30 bg-cyan-400/10 px-4 py-2 text-sm text-cyan-200">
                Compliance activity log
              </div>

              <h1 className="max-w-4xl text-5xl font-black tracking-tight md:text-6xl">
                Track every important invoice action.
              </h1>

              <p className="mt-5 max-w-2xl leading-7 text-slate-400">
                Maintain a clear history of uploads, audits, reports, review
                actions, rule updates, and system decisions.
              </p>
            </div>

            <div className="grid gap-4 sm:grid-cols-3 lg:grid-cols-1">
              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <CheckCircle2 className="text-emerald-300" />
                <p className="mt-4 text-3xl font-black">{successCount}</p>
                <p className="text-sm text-slate-400">Successful actions</p>
              </div>

              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <AlertTriangle className="text-yellow-300" />
                <p className="mt-4 text-3xl font-black">{warningCount}</p>
                <p className="text-sm text-slate-400">Warning events</p>
              </div>

              <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
                <History className="text-red-300" />
                <p className="mt-4 text-3xl font-black">{highRiskCount}</p>
                <p className="text-sm text-slate-400">High-risk events</p>
              </div>
            </div>
          </div>

          <div className="mt-8 rounded-3xl border border-white/10 bg-white/[0.05] p-5 backdrop-blur-xl">
            <div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-center">
              <div>
                <h2 className="text-2xl font-black">Activity Logs</h2>
                <p className="mt-1 text-sm text-slate-400">
                  Search and filter compliance activity.
                </p>
              </div>

              <div className="flex flex-col gap-3 md:flex-row md:items-center">
                <div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-slate-950/70 px-4 py-3">
                  <Search size={18} className="text-slate-400" />
                  <input
                    value={search}
                    onChange={(event) => setSearch(event.target.value)}
                    placeholder="Search logs..."
                    className="bg-transparent text-sm outline-none placeholder:text-slate-500"
                  />
                </div>

                <div className="flex flex-wrap gap-2">
                  {filters.map((item) => (
                    <button
                      key={item}
                      onClick={() => setFilter(item)}
                      className={`rounded-full px-4 py-2 text-sm font-bold transition ${
                        filter === item
                          ? "bg-cyan-400 text-slate-950"
                          : "border border-white/10 bg-white/[0.04] text-slate-400 hover:bg-white/10 hover:text-white"
                      }`}
                    >
                      {item}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            <div className="mt-6 grid gap-4">
              {filteredLogs.map((log) => {
                const Icon = typeIcon(log.type);

                return (
                  <div
                    key={log.id}
                    className="rounded-3xl border border-white/10 bg-slate-900/70 p-5"
                  >
                    <div className="grid gap-5 xl:grid-cols-[1fr_auto] xl:items-center">
                      <div className="flex gap-4">
                        <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-cyan-400/10 text-cyan-300">
                          <Icon size={26} />
                        </div>

                        <div>
                          <div className="flex flex-wrap items-center gap-3">
                            <h3 className="text-xl font-black">{log.action}</h3>

                            <span
                              className={`rounded-full border px-3 py-1 text-xs font-bold ${statusClass(
                                log.status
                              )}`}
                            >
                              {log.status}
                            </span>

                            <span className="rounded-full border border-white/10 bg-white/[0.04] px-3 py-1 text-xs font-bold text-slate-300">
                              {log.type}
                            </span>
                          </div>

                          <p className="mt-2 text-sm text-slate-400">
                            {log.id} · {log.actor} · {log.target}
                          </p>

                          <div className="mt-4 flex items-center gap-2 text-sm text-slate-500">
                            <Clock size={16} />
                            {log.time}
                          </div>
                        </div>
                      </div>

                      <a
                        href="/reports"
                        className="flex items-center justify-center rounded-full border border-white/10 bg-white/[0.04] px-5 py-3 text-sm font-bold text-white hover:bg-white/10"
                      >
                        View Related Report
                      </a>
                    </div>
                  </div>
                );
              })}
            </div>

            {filteredLogs.length === 0 && (
              <div className="mt-6 rounded-3xl border border-white/10 bg-slate-900/70 p-10 text-center">
                <History className="mx-auto text-cyan-300" size={48} />
                <h3 className="mt-4 text-2xl font-black">No logs found</h3>
                <p className="mt-2 text-sm text-slate-400">
                  Try changing the search term or filter.
                </p>
              </div>
            )}
          </div>
        </section>
      </div>
    </main>
  );
}